### ISSUE TITLE
'sengled-adapter died, code = 1' continuous loop

### ISSUE THREAD

**Issue by rdnlsmith** [mozilla-iot/sengled-adapter#3]
Hi! I'm trying to set up a webthings gateway for the first time. I have the following:

* Raspberry Pi 3B+
* ConBee II Zigbee USB adapter
* Sengled Smart LED Soft White A19 (PN 19010205)
* WebThings Gateway v0.9.2
* Sengled adapter v0.2.0

My first question is, is this add-on meant for use with Sengled's zigbee bulbs, or only the wi-fi ones? I can't seem to figure out how to get the pi and the bulb talking to each other. I did create a Sengled account and enter my credentials into the configuration screen, although I was hoping that webthings would be able to detect the bulb without needing to use the Sengled app.

Regardless of my bulb, in the logs I saw the Sengled adapter dying repeatedly. I pasted one iteration of this cycle below. I hope this report is useful to you; please let me know if I can do anything to help, or if I've done something incorrectly&mdash;so far as I can find, it seems like there isn't much documentation for webthings yet.

Thanks!

```
2019-10-26 22:06:31.626 INFO   : sengled: IpcClient: Connected to server, registering...
2019-10-26 22:06:31.629 INFO   : sengled: IpcClient: Received manager message: b'{"messageType":"registerPluginReply","data":{"pluginId":"sengled-adapter","ipcBaseAddr":"gateway.plugin.sengled-adapter"}}'
2019-10-26 22:06:31.633 INFO   : sengled: IpcClient: Registered with PluginServer
2019-10-26 22:06:31.635 INFO   : sengled: AddonManagerProxy: add_adapter: sengled-adapter
2019-10-26 22:06:35.301 ERROR  : sengled: Traceback (most recent call last):
2019-10-26 22:06:35.303 ERROR  : sengled:   File "/home/pi/.mozilla-iot/addons/sengled-adapter/main.py", line 30, in <module>
2019-10-26 22:06:35.305 ERROR  : sengled:     _ADAPTER = SengledAdapter(verbose=True)
2019-10-26 22:06:35.307 ERROR  : sengled:   File "/home/pi/.mozilla-iot/addons/sengled-adapter/pkg/sengled_adapter.py", line 39, in __init__
2019-10-26 22:06:35.309 ERROR  : sengled:     self.client.login()
2019-10-26 22:06:35.318 ERROR  : sengled:   File "/home/pi/.mozilla-iot/addons/sengled-adapter/pkg/client.py", line 341, in login
2019-10-26 22:06:35.320 ERROR  : sengled:     self.get_devices(force_update=True)
2019-10-26 22:06:35.322 ERROR  : sengled:   File "/home/pi/.mozilla-iot/addons/sengled-adapter/pkg/client.py", line 441, in get_devices
2019-10-26 22:06:35.324 ERROR  : sengled:     for d in data['deviceList']:
2019-10-26 22:06:35.325 ERROR  : sengled: TypeError: 'NoneType' object is not iterable
2019-10-26 22:06:35.454 INFO   : Plugin: sengled-adapter died, code = 1 restarting after 10000
```

**Comment by mrstegeman** [comment]
This adapter is specifically for the wi-fi bulbs. Zigbee bulbs should be handled directly by the Zigbee adapter (via the Conbee dongle). The error is due to the fact that you don't actually have any wi-fi bulbs attached to your account.

**Comment by mrstegeman** [comment]
(Thank you for reporting the crash, though. I've handled that [here](https://github.com/mozilla-iot/sengled-adapter/pull/4).)
